root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
bin = "./bin/app"
cmd = "make build"
delay = 500
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
exclude_regex = ["_test.go"]
exclude_unchanged = true
include_ext = ["go", "tpl", "tmpl", "html"]
log = "build-errors.log"
pre_cmd = [
    "go mod tidy",
    "gofumpt -l -w .",
    "golangci-lint run --fix --skip-dirs='./internal/json/'",
]
stop_on_error = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
