linters-settings:
  govet:
    check-shadowing: false
    disable:
      - fieldalignment
    enable-all: true
  errcheck:
    check-blank: true
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
linters:
  fast: false
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  enable:
    - zerologlint
  disable:
    - cyclop
    - depguard
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gci
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - grouper
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - misspell
    - nlreturn
    - nonamedreturns
    - paralleltest
    - promlinter
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
run:
  skip-files:
    - "internal/json/json.go"
  issue-exit-code: 0
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: true
  go: "1.21"
