before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - #
    main: ./cmd/http/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
archives:
  - #
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
